---
# --------------------------------------------------------------
# Install Docker Compose
# --------------------------------------------------------------
- name: install docker compose
  get_url:
    url: https://github.com/docker/compose/releases/download/1.9.0/docker-compose-"{{ uname_kernel_name }}"-"{{ uname_machine }}"
    dest: /usr/local/bin/docker-compose
    mode: 0774
